api:
  # host: http://localhost
  host: http://tp_otp_cont
  path: /otp/routers/default
  port: 8080

persistence:
  enabled: true
  strategy: localStorage

map:
  initLat: -16.50251
  initLon: -68.13223
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
      hasRetinaSupport: true
    - name: Stamen Toner Lite
      url: http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
    - name: OpenStreetMaps
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'
      attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
      maxZoom: 20


# it is possible to leave out a geocoder config entirely. In that case only
# GPS coordinates will be used when finding the origin/destination.

# example config for a Pelias geocoder (https://pelias.io/)
geocoder:
  apiKey: MAPZEN_KEY
  boundary:
    rect:
      minLon: -123.2034
      maxLon: -122.135
      minLat: 45.273
      maxLat: 45.7445
  focusPoint:
    lat: 45.5223452
    lon: -122.6821804
  # as i dont know the use of this geocoder i'll be using the default noApi geocoder NoApiGeocoder()
  # required geocoder type.
  # type: PELIAS
  type: noGeocoder
  # This base URL is required as the libraries will default to using now-defunct
  # mapzen urls
  baseUrl: https://geocoder.example.com/pelias/v1

# Use this mode config for the enhanced Transit+ config
modes:
  transitModes:
    - mode: BUS
      label: Bus
    - mode: TRAM
      label: MAX & Streetcar
    - mode: RAIL
      label: WES
    - mode: GONDOLA
      label: Aerial Tram

  accessModes:
    - mode: BICYCLE
      label: Transit + Bike

  bicycleModes:
    - mode: BICYCLE
      label: Own Bike
      iconWidth: 18


routingTypes:
  - key: ITINERARY
    text: Exact Time

### Use this config for the standard mode selector
# modeGroups:
#   - name: Transit
#     modes:
#       - TRAM
#       - BUS
#   - name: Walk/Bike
#     modes:
#       - WALK
#       - BICYCLE
